import { GoogleGenerativeAI } from "@google/generative-ai";
const pdfParse = require("pdf-parse");

// Initialize Gemini
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY || "");
const model = genAI.getGenerativeModel({ model: "gemini-3-flash-preview" });

export interface AnalysisResult {
    verdict: string;
    reasoning: string;
    score: number;
    isHuman: boolean;
    rawResponse: string;
}

const JSON_PROMPT_SUFFIX = `
Return the result strictly in the following JSON format:
{
  "verdict": "string",
  "reasoning": "string",
  "score": number (0-100, where 100 is definitely human),
  "isHuman": boolean
}
Do not include markdown formatting like \`\`\`json.
`;

export async function scanPDF(buffer: Buffer): Promise<AnalysisResult> {
    try {
        const data = await pdfParse(buffer);
        const text = data.text;

        const prompt = `Expert AI Forensic Analysis: Is this text AI-generated? Analyze perplexity and burstiness. ${JSON_PROMPT_SUFFIX}\n\n${text}`;

        console.log("Sending PDF text to Gemini...");
        const result = await model.generateContent(prompt);
        const response = result.response;
        const textResponse = response.text();
        console.log("Gemini Raw Response (PDF):", textResponse);

        try {
            const jsonResponse = JSON.parse(textResponse.replace(/```json/g, '').replace(/```/g, '').trim());
            return {
                ...jsonResponse,
                rawResponse: textResponse,
            };
        } catch (e) {
            console.error("Failed to parse JSON response", e);
            return {
                verdict: "Error",
                reasoning: "Failed to parse AI response",
                score: 0,
                isHuman: false,
                rawResponse: textResponse,
            };
        }
    } catch (error) {
        console.error("Error scanning PDF:", error);
        throw new Error("Failed to scan PDF");
    }
}

export async function scanImage(buffer: Buffer, mimeType: string): Promise<AnalysisResult> {
    try {
        const prompt = `Expert AI Forensic Analysis: Is this image AI-generated? Check for anatomical errors (fingers/eyes), lighting inconsistencies, and 'plastic' textures. ${JSON_PROMPT_SUFFIX}`;

        const imagePart = {
            inlineData: {
                data: buffer.toString("base64"),
                mimeType,
            },
        };

        const result = await model.generateContent([prompt, imagePart]);
        const response = result.response;
        const textResponse = response.text();
        console.log("Gemini Raw Response (Image):", textResponse);

        try {
            const jsonResponse = JSON.parse(textResponse.replace(/```json/g, '').replace(/```/g, '').trim());
            return {
                ...jsonResponse,
                rawResponse: textResponse,
            };
        } catch (e) {
            console.error("Failed to parse JSON response", e);
            return {
                verdict: "Error",
                reasoning: "Failed to parse AI response",
                score: 0,
                isHuman: false,
                rawResponse: textResponse,
            };
        }
    } catch (error) {
        console.error("Error scanning Image:", error);
        throw new Error("Failed to scan Image");
    }
}

export async function scanCode(codeContent: string): Promise<AnalysisResult> {
    try {
        const prompt = `
    Expert Code Forensic Analysis: Determine if this source code was likely generated by an AI (Copilot/ChatGPT) or a human.

    Look for:
    1. Variable Naming: Are they overly descriptive/generic (AI) or contextually unique (Human)?
    2. Comments: Do they explain the 'Why' (Human) or just the 'What' (AI)?
    3. Error Handling: Is it generic boilerplate or are there specific edge-case fixes?
    4. Implementation: Is it a 'textbook' implementation of a common algorithm?

    CODE:
    ${codeContent}

    ${JSON_PROMPT_SUFFIX}
    `;

        const result = await model.generateContent(prompt);
        const response = result.response;
        const textResponse = response.text();
        console.log("Gemini Raw Response (Code):", textResponse);

        try {
            const jsonResponse = JSON.parse(textResponse.replace(/```json/g, '').replace(/```/g, '').trim());
            return {
                ...jsonResponse,
                rawResponse: textResponse,
            };
        } catch (e) {
            console.error("Failed to parse JSON response", e);
            return {
                verdict: "Error",
                reasoning: "Failed to parse AI response",
                score: 0,
                isHuman: false,
                rawResponse: textResponse,
            };
        }
    } catch (error) {
        console.error("Error scanning Code:", error);
        throw new Error("Failed to scan Code");
    }
}
