import { AnalysisResult } from "./gemini-scanner";

const PERPLEXITY_API_URL = "https://api.perplexity.ai/chat/completions";
const MODEL = "sonar-pro"; // Or distinct model as needed

const JSON_PROMPT_SUFFIX = `
Return the result strictly in the following JSON format:
{
  "verdict": "string",
  "reasoning": "string",
  "score": number (0-100, where 100 is definitely human),
  "isHuman": boolean
}
Do not include markdown formatting like \`\`\`json.
`;

async function callPerplexity(messages: { role: string; content: string }[]): Promise<string> {
    const apiKey = process.env.PERPLEXITY_API_KEY;
    if (!apiKey) {
        throw new Error("PERPLEXITY_API_KEY is not set");
    }

    const response = await fetch(PERPLEXITY_API_URL, {
        method: "POST",
        headers: {
            "Authorization": `Bearer ${apiKey}`,
            "Content-Type": "application/json",
        },
        body: JSON.stringify({
            model: MODEL,
            messages: messages,
        }),
    });

    if (!response.ok) {
        throw new Error(`Perplexity API Error: ${response.statusText}`);
    }

    const data = await response.json();
    return data.choices[0].message.content;
}

function parseResult(textResponse: string): AnalysisResult {
    try {
        const jsonResponse = JSON.parse(textResponse.replace(/```json/g, '').replace(/```/g, '').trim());
        return {
            ...jsonResponse,
            rawResponse: textResponse,
        };
    } catch (e) {
        console.error("Failed to parse Perplexity JSON response", e);
        return {
            verdict: "Error",
            reasoning: "Failed to parse AI response from Perplexity",
            score: 0,
            isHuman: false,
            rawResponse: textResponse,
        };
    }
}

export async function scanTextWithPerplexity(text: string): Promise<AnalysisResult> {
    try {
        const prompt = `Expert AI Forensic Analysis: Is this text AI-generated? Analyze perplexity and burstiness. ${JSON_PROMPT_SUFFIX}\n\n${text}`;

        const content = await callPerplexity([
            { role: "system", content: "You are an expert at detecting AI-generated text." },
            { role: "user", content: prompt }
        ]);

        console.log("Perplexity Raw Response (Text):", content);

        return parseResult(content);
    } catch (error) {
        console.error("Error scanning text with Perplexity:", error);
        throw error;
    }
}

export async function scanCodeWithPerplexity(codeContent: string): Promise<AnalysisResult> {
    try {
        const prompt = `
    Expert Code Forensic Analysis: Determine if this source code was likely generated by an AI (Copilot/ChatGPT) or a human.

    Look for:
    1. Variable Naming: Are they overly descriptive/generic (AI) or contextually unique (Human)?
    2. Comments: Do they explain the 'Why' (Human) or just the 'What' (AI)?
    3. Error Handling: Is it generic boilerplate or are there specific edge-case fixes?
    4. Implementation: Is it a 'textbook' implementation of a common algorithm?

    CODE:
    ${codeContent}

    ${JSON_PROMPT_SUFFIX}
    `;

        const content = await callPerplexity([
            { role: "system", content: "You are an expert at detecting AI-generated code." },
            { role: "user", content: prompt }
        ]);

        console.log("Perplexity Raw Response (Code):", content);

        return parseResult(content);
    } catch (error) {
        console.error("Error scanning code with Perplexity:", error);
        throw error;
    }
}
